<a href="https://colab.research.google.com/github/luccasena/Fabrica-de-Software-Dados/blob/main/introducao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introdução com Python:

In [ ]:
# 1. Imprima na tela a mensagem: "Hello World"

print("Hello World")

Hello World


In [ ]:
# 2. Solicite ao usuário seu nome e imprima na tela:

name = str(input("Digite seu nome: "))
print(name)

Digite seu nome: Lucca
Lucca


In [ ]:
# 3. Imprima a soma na tela:

n1 = int(input("Digite um número: "))
n2 = int(input("Digite um número: "))
print(f"Soma: {n1 + n2}")

Digite um número: 2
Digite um número: 2
Soma: 4


In [ ]:
# 4. Solicite ao usuário um número e retorne se é par ou ímpar:

n1 = int(input("Digite um número: "))
if n1 % 2 == 0:
  print("Par")
else:
  print("Ímpar")

Digite um número: 749
Ímpar


## Pandas

In [ ]:
import pandas as pd

In [ ]:
golf_dict = { "ceu":["nuvem", "nuvem", "sol", "chuva", "sol", "sol"],
              "temperatura":[83, 94, 70, 68, 85, 80],
              "umidade":[86, 65, 90, 75, None, 90],
              "vento":[None, True, False, False, False, True],
              "joga":["sim", "sim", "sim", "sim","nao", "nao"]}

df = pd.DataFrame(golf_dict)
df

ceu  temperatura  umidade  vento joga
0  nuvem           83     86.0   None  sim
1  nuvem           94     65.0   True  sim
2    sol           70     90.0  False  sim
3  chuva           68     75.0  False  sim
4    sol           85      NaN  False  nao
5    sol           80     90.0   True  nao

In [ ]:
import numpy as np

In [ ]:
a = np.array([
        [
            [10, 20, 30, 40], [8, 8, 2, 1], [1, 1, 1, 2]
        ],
        [
            [9,9, 2, 39], [1, 2, 3, 3], [0, 0, 3, 2]
        ],
        [
            [12, 33, 22, 1], [22, 1, 22, 2], [0, 2, 3, 1]
        ]

], dtype=float)
print(a)

[[[10. 20. 30. 40.]
  [ 8.  8.  2.  1.]
  [ 1.  1.  1.  2.]]

 [[ 9.  9.  2. 39.]
  [ 1.  2.  3.  3.]
  [ 0.  0.  3.  2.]]

 [[12. 33. 22.  1.]
  [22.  1. 22.  2.]
  [ 0.  2.  3.  1.]]]


### Matplotlib

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sn